networks:
  protheus_network:
    name: protheus_backend_net
    driver: bridge

volumes:
  oracle_data:
    name: protheus_oracle_volume

services:
  protheus_oracle:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: protheus_oracle
    restart: always
    networks:
      - protheus_network
    ports:
      - "${ORACLE_PORT}:1521"
    env_file:
      - .env.oracle
    volumes:
      - oracle_data:/opt/oracle/oradata